### ISSUE TITLE
Rollup where no ParentID in Child

### ISSUE THREAD

**Issue by dschueler** [abhinavguptas/Salesforce-Lookup-Rollup-Summaries#15]
I am rolling up Cases onto Contact. All is well normally, but if it's an email-to-case there may not be a ContactId on the case record....this creates an APEX Error. 

What is the best way to work around this in LRE?

**Comment by abhinavguptas** [comment]
@dschueler it needs a relating "ID" field to work. It would be same as manually writing apex trigger, we can't relate case back to contact, unless the contactId is populated on the case.

**Comment by dschueler** [comment]
@abhinavguptas yes, i get that... i was just wondering if you had example or recommended code to filter out recs from trigger.new/old where contactID is null.

**Comment by abhinavguptas** [comment]
Unfortunately no, you need some way to relate Case with Contact, if its not ContactId, then it goes out of scope for LREngine to pick it up. I would suggest writing a custom trigger for any custom parent-child matching logic.
