### ISSUE TITLE
When Change the Lookup to Another Parent, Rollup Count is not Decremented on the old Parent record

### ISSUE THREAD

**Issue by doomsday-git** [abhinavguptas/Salesforce-Lookup-Rollup-Summaries#17]
I implemented the recommended changes with LREngine. It is working great when I do insert/delete, the parent is getting the roll-up correctly. 

But I am seeing one problem and that is if I change the child Lookup from parent A to parent B, parent B roll-up count is incremented by one correctly, but the original parent A roll-up count does not decrement by one.

Is there any way to handle in case of re-parenting?

**Comment by abhinavguptas** [comment]
@doomsday-git we will check on this one and let you know. If you want to fix the same, please feel free and submit a pull request. I will possibly get time after Dreamforce to check this.

**Comment by adorigo** [comment]
Also you can add, in case of change of parent, the old child record to the list to rollUp on so the fields of the old parent are refreshed.  I think this should'nt be a problem because the "child objects list" is used to grab the masters Ids.

Hope that helps you!

**Comment by akkibaddi** [comment]
@abhinavguptas  Any update on this, can we achieve this by checking in trigger if old parent lookup is different from the new one then call the LREngine with old value (lookUp Id)  to recalculate the Rollup's?

I think this issue shouldn't be a problem for Batch context.

Let me know your thoughts on this , thanks !

**Comment by abhinavguptas** [comment]
Thanks @akkibaddi, I believe the best way to address this could be to form a single Set<Id> combining OLD and NEW parent record Ids, i.e. "masterIds" in Trigger context and call the following method in a batch or future context

`
    public static Sobject[] rollUp(Context ctx,  Set<Id> masterIds) {}

`

**Comment by akkibaddi** [comment]
@abhinavguptas Thanks for the information, I tried to call this above method in trigger context with out using future or Batch context, it's working great.

 I created a pull request for Read me file in Trigger context if you feel this works please verify my pull request and see if we can close this issue.

Thanks!

**Comment by abhinavguptas** [comment]
@akkibaddi  I reviewed your changes. Unfortunately, they are not covering the full picture and it's looking like a lot of code. I will take a look again at the solution and documentation, and will get back to you.
