### ISSUE TITLE
Multiple rollups with different filters

### ISSUE THREAD

**Issue by nicholassewitz** [abhinavguptas/Salesforce-Lookup-Rollup-Summaries#18]
Hey @abhinavguptas how would you recommend proceeding when I have multiple rollups that need to be done for the same relationship. For instance I need to do 

1. Count of Contacts from India
2. Count of Contacts from USA

It seems like the only way to do this would be to write a whole new ctx, but it would be a lot easier if within the ctx we could add in rollups with filters so something like 

```
ctx.add(
new LREngine.RollupSummaryField(                            																			 Schema.SObjectType.Account.fields.Count_of_Upcoming_Fairs__c,                            																			 Schema.SObjectType.Show__c.fields.Id,
'Country = India',
LREngine.RollupOperation.Count));
```

Am I right in my assumptions?

**Comment by abhinavguptas** [comment]
We do support filters, did you tried following format of context @nicholassewitz 

`LREngine.Context ctx = new LREngine.Context(Account.SobjectType, 
	                        Opportunity.SobjectType, 
	                        Schema.SObjectType.Opportunity.fields.AccountId,
	                        'Amount > 200' // filter out any opps with amount less than 200
	                        );`
