### ISSUE TITLE
SUGGESTION: How about adding in a 'CONCATENATE' operator

### ISSUE THREAD

**Issue by dschueler** [abhinavguptas/Salesforce-Lookup-Rollup-Summaries#20]
I am writing a trigger to rollup a list of email addresses from a related list and populating a field in the parent with a comma delimited email list that I use to blast to all the parties that want notifications. I use LREngine for a bunch of other rollups and found myself wishing there was a concatenate option. 👍

**Comment by aheber** [comment]
@dschueler have you looked into Declarative Lookup Rollup Summaries?
https://github.com/afawcett/declarative-lookup-rollup-summaries

It provides a declarative interface around this library and already supports concatenate.

**Comment by dschueler** [comment]
I have not…looking at it right now…looks pretty good..thanks!

**Comment by aheber** [comment]
👍
