### ISSUE TITLE
Too Many SOQL Statments

### ISSUE THREAD

**Issue by dschueler** [abhinavguptas/Salesforce-Lookup-Rollup-Summaries#22]
I have a rollup in a trigger for Cases that summarizes to the Contact object. All good. Since it has filters,  I have 4 "LR Context's and 4 ct1.add(new LREngine.RollupSummaryField 's and 4   Sobject[] masters1 = LREngine.rollUp(ct1, objects); and then 4 Update Statements. 

Introduce a Process Builder Flow that can "autocreate" 7 cases with different case types all in 1 PB process. 

This then 'breaks' because of this trigger with the rollups.

Question is, is there a different way I should be handling this trigger to minimize the SOQL to avoid this fail?

**Comment by abhinavguptas** [comment]
Can you please share more details about the process builder? I am not very clear on what is going on. Probably a screenshot of the process builder, with some extra details?

**Comment by dschueler** [comment]
Abhinav, I worked around this issue by moving the autocreate of multiple cases from Process Builder back into a Trigger. It looks like the problem was in how process builder was running in conjunction with the Rollup Trigger. The tipping point was creation of 3 cases within the PB side ..that would blow up a Rollup Trigger with just 1 rollup and nothing else in it. Here is a screenshot of part of the PB side. As I said, for me its now working for me since I am now creating those cases in an After Insert/After Update Trigger. 
![2019-05-22_10-19-49](https://user-images.githubusercontent.com/371030/58182384-8246a400-7c7b-11e9-9b27-22b5c68c6bdd.png)

**Comment by abhinavguptas** [comment]
Thanks for updating back @dschueler. We ran into similar situations multiple times lately with PB. Most of the processes start trivial but go complex with multiple admins/devs adding to them, and eventually, they blew up. 

Solution is same, move stuff to classic triggers.
