### ISSUE TITLE
Conditional Filtering

### ISSUE THREAD

**Issue by colinkenworthy** [abhinavguptas/Salesforce-Lookup-Rollup-Summaries#26]
I was trying to filter on picklist values not being certain values
`'NOT PicklistField__c IN (\'Val3\',\'Val5\')'`
this throws exception about the 'NOT'

I ended up using the opposite
`'PicklistField__c IN (\'Val1\',\'Val2\',\'Val4\')'`

Would it be possible to cater for the where clause with the 'NOT' ?

**Comment by rkshakya07** [comment]
Hi @colinkenworthy .
 try this: 
`'PicklistField__c NOT IN (\'Val3\',\'Val5\')'`

**Comment by colinkenworthy** [comment]
> Hi @colinkenworthy .
> try this:
> `'PicklistField__c NOT IN (\'Val3\',\'Val5\')'`

Thank you, that worked.
